// FOR FETCHING THE TASKS

export const GET_TASK_REQUEST = "GET_TASK_REQUEST"
export const GET_TASK_SUCCESS = "GET_TASK_SUCCESS"
export const GET_TASK_FAILURE = "GET_TASK_FAILURE"

// FOR ADDING A NEW TASK

export const POST_TASK_SUCCESS = "POST_TASK_SUCCESS"

// FOR DELETING A TASK

export const DELETE_TASK_SUCCESS = "DELETE_TASK_SUCCESS"

// FOR UPDATING A TASK

export const UPDATE_TASK_SUCCESS = "UPDATE_TASK_SUCCESS"